apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sscs-sa
secrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-sscs-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-sscs-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles