apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sscs-sa
secrets:
  - name: docker-basic-user-pass
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-sscs-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-sscs-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
  namespace: sscs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sscs-pod-create
  namespace: sscs-app
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-sscs-sscs-sa-create-pod-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
  namespace: sscs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sscs-pod-create