apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-sscs-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sscs-sa
  namespace: sscs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles