apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: sscs
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "true"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: 4f4b-156-146-50-4.ngrok.io
  - name: Service
    value: sscs
  - name: ServicePort
    value: "8080"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook