apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: sscs
stringData:
  token: <REPLACE TOKEN>
  secret: random-string-data
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-basic-user-pass
  annotations:
    tekton.dev/docker-0: https://index.docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: <REPLACE NAME>
  password: <REPLACE PASSWORD>